---
- hosts: "{{ hostname }}"
  gather_facts: no
  tasks:
    - name: create file
      copy:
        dest: "{{ dest_path }}"
        src: "{{ src_path }}"
        mode: "{{ file_mode }}"
        owner: "{{ file_owner }}"
        group: "{{ file_group_owner }}"
        serole: "{{ file_serole | default(omit) }}"
        setype: "{{ file_setype | default(omit) }}"
        seuser: "{{ file_seuser | default(omit) }}"
        selevel: "{{ file_selevel | default(omit) }}"
